dist: trusty
osx_image: xcode8.2
sudo: false
language: python

matrix:
  fast_finish: true
  include:
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7-dev
    - os: linux
      python: nightly
    - os: osx
      python: nightly

install:
  - pip install .
  - pip install .[dev]

script:
  - py.test --cov pyffi --cov-report=term tests
  - coverage report --show-missing

after_success:
  - coveralls
  - python setup.py sdist bdist_wheel

notifications:
    email: false
