dist: trusty
osx_image: xcode8.2
os:
  - linux
  - osx
sudo: false
language: python
python:
  - "nightly"

matrix:
  fast_finish: true

install:
  - pip install -r requirements-dev.txt

script:
  - py.test --cov pyffi --cov-report=term tests
  - coverage report --show-missing

after_success:
  - coveralls

notifications:
    email: false
