environment:
  matrix:
    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      PYTEST: "%PYTHON%\\Scripts\\py.test"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      PYTEST: "%PYTHON%\\Scripts\\py.test"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      PYTEST: "%PYTHON%\\Scripts\\py.test"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_VERSION: "3.3"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      PYTEST: "%PYTHON%\\Scripts\\py.test"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      PYTEST: "%PYTHON%\\Scripts\\py.test"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      RUN: "%PYTHON%\\python"
      PIP: "%PYTHON%\\Scripts\\pip"
      PYTEST: "%PYTHON%\\Scripts\\py.test"

matrix:
  fast_finish: true

install:
  - "ECHO %PYTHON% %PYTHON_VERSION%%APPVEYOR_BUILD_FOLDER%"
  - "set HOME=%APPVEYOR_BUILD_FOLDER%"
  - "%PIP% install -r requirements-dev.txt"
  - "cd %HOME%"

test: off

build_script:
  - "%PYTEST% --cov pyffi --cov-report=term tests"

#on_success:
#  - "coveralls"
#  - "%RUN% -c \"import codecov; codecov.main(token='9c51d155-86c2-4b30-ae60-cba2a13e21a9')\""
